export { fontLoader } from './font'
export { imageLoader } from './image'
export { scssLoader } from './scss'
export { svgLoader } from './svg'
export { svgrLoader } from './svgr'
export { tsLoader } from './ts'
